### ISSUE TITLE
Crash problem when it start to CoreCommand::calculateProperties

### ISSUE THREAD

**Issue by yuan0258** [alexa/apl-core-library#3]
Crash problem when it start to CoreCommand::calculateProperties

I'm trying to integrate alexa device sdk 1.19.1 + smart screen sdk 2.1 + apl-core-library 1.3.2 to our platform(ARM CA7 dual core 1GHz)
The toolchain is https://releases.linaro.org/components/toolchain/binaries/6.3-2017.05/arm-linux-gnueabihf/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf.tar.xz
When I ask 'alexa, what's the weather'
When it start to rendering. It will case coredump in my system

Here is the statck trace from core-file.
`#0  0x00074db8 in __gnu_cxx::__exchange_and_add (__val=-1, __mem=0x21)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/ext/atomicity.h:49
#1  __gnu_cxx::__exchange_and_add_dispatch (__val=-1, __mem=0x21)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/ext/atomicity.h:82
#2  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x1d)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/shared_ptr_base.h:147
#3  0xb53adca6 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0xafb5c344, __in_chrg=<optimized out>)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/shared_ptr_base.h:662
#4  0xb543e444 in std::__shared_ptr<apl::Object::Data, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0xafb5c340, __in_chrg=<optimized out>)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/shared_ptr_base.h:928
#5  0xb543e478 in std::shared_ptr<apl::Object::Data>::~shared_ptr (this=0xafb5c340, __in_chrg=<optimized out>)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/shared_ptr.h:93
#6  0xb54378d2 in apl::Object::~Object (this=0xafb5c318, __in_chrg=<optimized out>) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/src/primitives/object.cpp:739
#7  0xb53b5552 in std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object>::~pair (this=0xafb5c300, __in_chrg=<optimized out>)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/stl_pair.h:194
#8  0xb53c020a in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > (this=0xafb5c2ec, __p=0xafb5c300)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/ext/new_allocator.h:124
#9  0xb53bf1f2 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > (__a=..., __p=0xafb5c300)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/alloc_traits.h:487
#10 0xb53bd15a in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > >::_M_destroy_node (this=0xafb5c2ec, __p=0xafb5c2f0)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/stl_tree.h:567
#11 0xb53b9e8a in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > >::_M_drop_node (this=0xafb5c2ec, __p=0xafb5c2f0)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/stl_tree.h:575
#12 0xb549eb10 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > >::_M_erase_aux (this=0xafb5c2ec, __position=...)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/stl_tree.h:2275
#13 0xb54fc680 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > >::erase[abi:cxx11](std::_Rb_tree_const_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> >) (this=0xafb5c2ec,
    __position=...) at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/stl_tree.h:1036
#14 0xb54f9e92 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > >::_M_erase_aux (this=0xafb5c2ec, __first=..., __last=...)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/stl_tree.h:2289
#15 0xb54f853a in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > >::erase[abi:cxx11](std::_Rb_tree_const_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> >, std::_Rb_tree_const_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> >) (this=0xafb5c2ec, __first=..., __last=...)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/stl_tree.h:1069
#16 0xb54f6b38 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > >::erase (this=0xafb5c2ec, __x=...) at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/stl_tree.h:2300
#17 0xb54f4c0e in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, apl::Object, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, apl::Object> > >::erase (this=0xafb5c2ec, __x=...)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/bits/stl_map.h:981
#18 0xb54ea006 in apl::CoreCommand::calculateProperties (this=0xafbbafb4) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/src/command/corecommand.cpp:205
#19 0xb54f1c76 in apl::SetValueCommand::execute (this=0xafbbafb4, timers=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/command/setvaluecommand.h:52
#20 0xb54e1158 in apl::DelayAction::checkCommand (this=0xafb56c1c) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/action/delayaction.h:100
#21 0xb54e0d10 in apl::DelayAction::start (this=0xafb56c1c) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/action/delayaction.h:64
#22 0xb54e0b90 in apl::DelayAction::make (timers=..., command=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/action/delayaction.h:37
#23 0xb54ed1ec in apl::ParallelCommand::execute (this=0xb462df4c, timers=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/command/parallelcommand.h:57
#24 0xb54e1158 in apl::DelayAction::checkCommand (this=0xb462e6a4) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/action/delayaction.h:100
#25 0xb54e0d10 in apl::DelayAction::start (this=0xb462e6a4) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/action/delayaction.h:64
#26 0xb54e0b90 in apl::DelayAction::make (timers=..., command=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/action/delayaction.h:37
#27 0xb54e03e4 in apl::ArrayAction::advance (this=0xafb43de4) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/src/action/arrayaction.cpp:67
#28 0xb545fe94 in apl::ArrayAction::make (timers=..., command=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/action/arrayaction.h:31
#29 0xb545fcc4 in apl::ArrayCommand::execute (this=0xafb43cf0, timers=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/src/command/arraycommand.cpp:37
#30 0xb54e1158 in apl::DelayAction::checkCommand (this=0xafb43d74) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/action/delayaction.h:100
#31 0xb54e0d10 in apl::DelayAction::start (this=0xafb43d74) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/action/delayaction.h:64
#32 0xb54e0b90 in apl::DelayAction::make (timers=..., command=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/action/delayaction.h:37
#33 0xb54e03e4 in apl::ArrayAction::advance (this=0xafb60a0c) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/src/action/arrayaction.cpp:67
#34 0xb545fe94 in apl::ArrayAction::make (timers=..., command=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/include/apl/action/arrayaction.h:31
#35 0xb545fcc4 in apl::ArrayCommand::execute (this=0xb462e9b8, timers=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/src/command/arraycommand.cpp:37
#36 0xb544dafa in apl::Sequencer::execute (this=0xb4641fc8, commandPtr=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/src/time/sequencer.cpp:42
#37 0xb544df1c in apl::Sequencer::executeCommands (this=0xb4641fc8, commands=..., context=..., baseComponent=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/src/time/sequencer.cpp:84
#38 0xb541150c in apl::RootContext::executeCommands (this=0xb4639d20, commands=..., fastMode=false)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/aplcore/src/engine/rootcontext.cpp:220
#39 0xb5399aa4 in APLClient::AplCoreConnectionManager::executeCommands (this=0x273a60, command=..., token=...)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/alexa-smart-screen-sdk-master/modules/Alexa/ApplicationUtilities/APLClient/src/AplCoreConnectionManager.cpp:286
#40 0xb5391b82 in APLClient::AplClientBinding::executeCommands (this=<optimized out>, jsonPayload=..., token=...)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/alexa-smart-screen-sdk-master/modules/Alexa/ApplicationUtilities/APLClient/src/AplClientBinding.cpp:48
#41 0x00061c2a in alexaSmartScreenSDK::sampleApp::AplClientBridge::<lambda()>::operator() (__closure=<optimized out>)
    at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/alexa-smart-screen-sdk-master/modules/Alexa/SampleApp/src/AplClientBridge.cpp:219
#42 std::_Bind<alexaSmartScreenSDK::sampleApp::AplClientBridge::executeCommands(const string&, const string&)::<lambda()>()>::__call<void> (__args=<optimized out>, this=<optimized out>)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/functional:934
#43 std::_Bind<alexaSmartScreenSDK::sampleApp::AplClientBridge::executeCommands(const string&, const string&)::<lambda()>()>::operator()<> (this=<optimized out>)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/functional:993
#44 std::__invoke_impl<void, std::_Bind<alexaSmartScreenSDK::sampleApp::AplClientBridge::executeCommands(const string&, const string&)::<lambda()>()>&> (__f=...)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/functional:210
#45 std::__invoke<std::_Bind<alexaSmartScreenSDK::sampleApp::AplClientBridge::executeCommands(const string&, const string&)::<lambda()>()>&> (__fn=...)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/functional:251
#46 std::reference_wrapper<std::_Bind<alexaSmartScreenSDK::sampleApp::AplClientBridge::executeCommands(const string&, const string&)::<lambda()>()> >::operator()<> (this=<optimized out>)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/functional:465
#47 std::_Bind_simple<std::reference_wrapper<std::_Bind<alexaSmartScreenSDK::sampleApp::AplClientBridge::executeCommands(const string&, const string&)::<lambda()>()> >()>::_M_invoke<> (
    this=<optimized out>) at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/functional:1391
#48 std::_Bind_simple<std::reference_wrapper<std::_Bind<alexaSmartScreenSDK::sampleApp::AplClientBridge::executeCommands(const string&, const string&)::<lambda()>()> >()>::operator() (
    this=<optimized out>) at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/functional:1380
#49 std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::_Bind_simple<std::reference_wrapper<std::_Bind<alexaSmartScreenSDK::sampleApp::AplClientBridge::executeCommands(const string&, const string&)::<lambda()>()> >()>, void>::operator() (this=0xb1c23bd4)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/future:1348
#50 std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>(), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::_Bind_simple<std::reference_wrapper<std::_Bind<alexaSmartScreenSDK::sampleApp::AplClientBridge::executeCommands(const string&, const string&)::<lambda()>()> >()>, void> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/functional:1717
#51 0x00072576 in std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>::operator()() const (this=<optimized out>)
    at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/functional:2127
#52 std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (this=0xb43092fc,
    __f=<optimized out>, __did_set=0xb1c23b9b) at /mtkeda/dtv/msttools/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/6.3.1/future:533
#53 0xb56fed54 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
`

It seems the crash point is here https://github.com/alexa/apl-core-library/blob/master/aplcore/src/command/corecommand.cpp#L205

Could you give me some hint about this issue ?

**Comment by bddufour** [comment]
Thanks for reaching out. At first glance, it looks like there is some memory corruption happening, causing calculateProperties to crash. A more in-depth investigation will be needed to determine the source of the corruption. Given you're using the smart screen SDK, I suggest you instead file this with them so it can properly investigated and triaged starting from upstream.

**Comment by yuan0258** [comment]
@bddufour ,
Because the older sdk version is ok(apl-core 1.2 + smart screen sdk 2.0.2 + device sdk 1.19.0)
Does there is any limitaion about memory?
Our platform memory totoally is 256MB

**Comment by bddufour** [comment]
Once again, I unfortunately need to refer you to the Smart Screen SDK. APL Core is only one of the dependencies of the smart screen SDK, we can't meaningfully comment on overall system requirements.

**Comment by yuan0258** [comment]
if I comment out this line of corecommand.cpp#L205.
It seems the sdk could be workable now
But I wonder does it will impact something wrong.

**Comment by yuan0258** [comment]
Our platform kernel is 32bit.
I'm trying to use unittest to check in our platform.
It seems it will crash at when apl-core-library/unit/unittest_apl.cpp:146
Could you help to check it?
[bt_full_unittest.txt](https://github.com/alexa/apl-core-library/files/4750970/bt_full_unittest.txt)
[==========] Running 969 tests from 81 test cases.
[----------] Global test environment set-up.
[----------] 23 tests from ActionTest
[ RUN      ] ActionTest.MakeResolved
[       OK ] ActionTest.MakeResolved (1 ms)
[ RUN      ] ActionTest.MakeActionAndResolve
[       OK ] ActionTest.MakeActionAndResolve (0 ms)
[ RUN      ] ActionTest.MakeActionAndResolveArgument
[       OK ] ActionTest.MakeActionAndResolveArgument (0 ms)
[ RUN      ] ActionTest.MakeActionAndResolveRect
[       OK ] ActionTest.MakeActionAndResolveRect (0 ms)
[ RUN      ] ActionTest.DelayedMakeActionAndResolve
[       OK ] ActionTest.DelayedMakeActionAndResolve (0 ms)
[ RUN      ] ActionTest.DelayedActionTerminate
[       OK ] ActionTest.DelayedActionTerminate (1 ms)
[ RUN      ] ActionTest.DelayedActionTerminate2
[       OK ] ActionTest.DelayedActionTerminate2 (0 ms)
[ RUN      ] ActionTest.MakeAll
[       OK ] ActionTest.MakeAll (0 ms)
[ RUN      ] ActionTest.MakeAllTerminate
[       OK ] ActionTest.MakeAllTerminate (0 ms)
[ RUN      ] ActionTest.MakeAllEmpty
[       OK ] ActionTest.MakeAllEmpty (1 ms)
[ RUN      ] ActionTest.MakeAny
[       OK ] ActionTest.MakeAny (0 ms)
[ RUN      ] ActionTest.MakeAnyTerminate
[       OK ] ActionTest.MakeAnyTerminate (0 ms)
[ RUN      ] ActionTest.MakeAnyEmpty
[       OK ] ActionTest.MakeAnyEmpty (0 ms)
[ RUN      ] ActionTest.UserData
[       OK ] ActionTest.UserData (0 ms)
[ RUN      ] ActionTest.UserDataDelayed
[       OK ] ActionTest.UserDataDelayed (0 ms)
[ RUN      ] ActionTest.Animation
[       OK ] ActionTest.Animation (1 ms)
[ RUN      ] ActionTest.AnimationNonZeroOffset
[       OK ] ActionTest.AnimationNonZeroOffset (0 ms)
[ RUN      ] ActionTest.AnimationWithTimeOffset
[       OK ] ActionTest.AnimationWithTimeOffset (0 ms)
[ RUN      ] ActionTest.AnimationStop
[       OK ] ActionTest.AnimationStop (0 ms)
[ RUN      ] ActionTest.DoubleResolve
[       OK ] ActionTest.DoubleResolve (0 ms)
[ RUN      ] ActionTest.DoubleTerminate
[       OK ] ActionTest.DoubleTerminate (0 ms)
[ RUN      ] ActionTest.ResolveAndTerminate
[       OK ] ActionTest.ResolveAndTerminate (0 ms)
[ RUN      ] ActionTest.TerminateAndResolve
[       OK ] ActionTest.TerminateAndResolve (0 ms)
[----------] 23 tests from ActionTest (5 ms total)

[----------] 1 test from APLTest
[ RUN      ] APLTest.Basic
*** Error in `./unittest': free(): invalid pointer: 0xbee7468c ***
Aborted (core dumped)

**Comment by yuan0258** [comment]
@bddufour ,
I could repoduce the same problem is my raspberry pi4 with same unittest
The toolchain is build from 6.3.1
The build apl-core option is "cmake -DBUILD_TESTS=ON -DCOVERAGE=OFF -DCMAKE_BUILD_TYPE=debug -DCMAKE_CXX_FLAGS="-fPIC -O0 -mcpu=cortex-a7 -mfloat-abi=hard -mfpu=neon-vfpv4 -static" ../"

**Comment by yuan0258** [comment]
I found this is cross compile toolchain issue about apl core code
If I use arm linaro toolchain(7.2.1) unittest result as below
Toolchain path:https://releases.linaro.org/components/toolchain/binaries/7.2-2017.11/arm-linux-gnueabihf/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf.tar.xz

[apl_v1.3.2_unittest_with_gcc_7.2.1.log](https://github.com/alexa/apl-core-library/files/4756326/apl_v1.3.2_unittest_with_gcc_7.2.1.log)
[==========] 969 tests from 81 test cases ran. (16052 ms total)
[  PASSED  ] 966 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] CommandTest.RepeatedSetValue
[  FAILED  ] DynamicIndexListTest.WrongUpdates
[  FAILED  ] DynamicIndexListTest.CrudMultiInsertBelow
 3 FAILED TESTS

Could your team check this issue by different toolchain?

**Comment by yuan0258** [comment]
@bddufour 
I dump stack of unittest
There was the different stack value
The problem occur when Object construct.

> TEST(ObjectTest,` SharedMap)
{
    Object a = Object(std::make_shared< std::map< std::string, Object> >(
            std::map<std::string, Object>({
        { "a", 1 }, { "b", false }, { "c", "fuzzy"}
    })));
}

ARM 6.3.1 Failure(https://releases.linaro.org/components/toolchain/binaries/6.3-2017.05/arm-linux-gnueabihf/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf.tar.xz)

> #11 0x00355dfc in ObjectTest_SharedMap_Test::TestBody (this=0xa69fe8) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/unit/unittest_object.cpp:105

        a = {mType = 3204443648, mValue = 4.7697700058647943e-299, mString = {static npos = 4294967295,
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xbeffee10 "0\361\377\276\\F\234"},
            _M_string_length = 3204443664, {_M_local_buf = "0\361\377\276\\F\234\000 \356\377\276L\361\377\276", _M_allocated_capacity = 3204444464}},
          mData = {<std::__shared_ptr<apl::Object::Data, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = 0xbefff100, _M_refcount = {_M_pi = 0xbeffee28}}, <No data fields>}}

ARM7.2.1 OK(https://releases.linaro.org/components/toolchain/binaries/7.2-2017.11/arm-linux-gnueabihf/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf.tar.xz)

> #0  ObjectTest_SharedMap_Test::TestBody (this=0xa60390) at /mfs/mcpslt0005/mtk17935/bringup/AVSSDK/alexa/apl-core-library/unit/unittest_object.cpp:105

        a = {mType = 3204444481, mValue = 1.7673815082811434e-301, mString = {static npos = 4294967295,
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xbefff110 "w"}, _M_string_length = 5, {
              _M_local_buf = "\370\355\377\276\327\062\001\000\000L~\000,\361\377\276", _M_allocated_capacity = 3204443640}},
          mData = {<std::__shared_ptr<apl::Object::Data, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<apl::Object::Data, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0xbefff13c, _M_refcount = {_M_pi = 0xbeffee08}}, <No data fields>}}

**Comment by yuan0258** [comment]
Finally. I find a solution to resolve this problem
Use clang to cross compile apl and link it by orignal toolchain.
You could close this issue now
