### ISSUE TITLE
unittest test result two fail item on raspberry pi4

### ISSUE THREAD

**Issue by yuan0258** [alexa/apl-core-library#4]
I test unittest binary on pi4.There are two failed item.
Could you help to check what is matter?
[unittest_on_rasberry_pi4.txt](https://github.com/alexa/apl-core-library/files/4777808/unittest_on_rasberry_pi4.txt)

[  FAILED  ] 2 tests, listed below:
[  FAILED  ] DynamicIndexListTest.WrongUpdates
[  FAILED  ] DynamicIndexListTest.CrudMultiInsertBelow

**Comment by bddufour** [comment]
Could you please try again with 1.3.3, released today? It does contain a fix for a bug that was causing at least CrudMultiInsertBelow to fail under some circumstances.

**Comment by yuan0258** [comment]
@bddufour 
I try 1.3.3 version. There still have one unittest fail.
[unittest_apl_1.3.3.txt](https://github.com/alexa/apl-core-library/files/4783804/unittest_apl_1.3.3.txt)
[----------] Global test environment tear-down
[==========] 969 tests from 81 test cases ran. (4084 ms total)
[  PASSED  ] 968 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DynamicIndexListTest.WrongUpdates

 1 FAILED TEST

**Comment by bddufour** [comment]
Ok, so 1.3.3 at least fixed one of the failures. Can you tell us more about your toolchain so I can try to reproduce?

**Comment by yuan0258** [comment]
Here is my pi4 gcc version
pi@raspberrypi:~ $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 8.3.0-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)

**Comment by yuan0258** [comment]
Here is my cmake option
cmake -DBUILD_TESTS=ON -DCOVERAGE=OFF ${APL_DIR} -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_FLAGS="-fPIC"

**Comment by yuan0258** [comment]
The APL 1.4.0 already pass all unitest case in pi4.
I close this issue now

[----------] Global test environment tear-down
[==========] 1213 tests from 95 test cases ran. (5618 ms total)
[  PASSED  ] 1213 tests.
